
package proyecto_ucq;

import claseConectar.conectar;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.omg.CORBA_2_3.portable.InputStream;


public class abc_copia extends javax.swing.JFrame {
    
    private FileInputStream fis;
    private int longitudBytes;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Imagen","jpg","png");
    String rutaimagen;
    DefaultTableModel model;
    conectar con;
    
    public abc_copia() {
        initComponents();
        mostrarDatos("");
        limpiar();
        bloquear();
        
    }
      public void filtro() {
        int columnaABuscar = 0;
        if (cmb_eSTATUS2.getSelectedItem() == "ACTIVO") {
            columnaABuscar = 0;
        }
        if (cmb_eSTATUS2.getSelectedItem().toString() == "NO ACTIVO") {
            columnaABuscar = 1;
        }
        if (cmb_eSTATUS2.getSelectedItem() == "TODOS") {
            columnaABuscar = 2;
        }
        
    }
 

    void limpiar(){
    txt_clave.setText("");
    txt_Nombre.setText("");
    txt_Usuario.setText("");
    ps_contra.setText("");
    lbfoto.setIcon(null);
    cmb_tu1.setSelectedItem("ALUMNO");
    cmb_estatus.setSelectedItem("ACTIVO");
    cmb_carrera.setSelectedItem("SELECCIONE UNA CARRERA...");
    txt_CorreoI.setText("");
    txt_CorreoP.setText("");
    txt_Telefono1.setText("");
    txt_Telefono2.setText("");  
    }
    void bloquear()
   {
      
       Btn_Editar.setEnabled(true);
      Btn_Agregar.setEnabled(true);
   }
   void desbloquear()
   {
       txt_clave.setEnabled(true);
       txt_Nombre.setEnabled(true);
       txt_Usuario.setEnabled(true);
       ps_contra.setEnabled(true); 
       txt_CorreoP.setEnabled(true);
       txt_CorreoI.setEnabled(true);
       txt_Telefono1.setEnabled(true);
       txt_Telefono2.setEnabled(true);
       cmb_tu1.setEnabled(true); 
       cmb_estatus.setEnabled(true);
       cmb_carrera.setEnabled(true);
       btn_guardar.setEnabled(true);
       Btn_Editar.setEnabled(true);
      Btn_Agregar.setEnabled(false);
   }
   
    void mostrarDatos(String valor){
       con = new conectar();
       Connection cn = con.getConnection();
                //Cabezas de Tabla
            String [] titulos={"Clave  de Usuario","Nombre Completo de Usuario","Usuario","Contraseña","Tipo de Usuario","Estatus","Correo Personal","Correo Institucional","Telefono Fijo" ,"Telefono Celular","Carrera"};
            String [] registros = new String[11];
            
            String sql="SELECT * FROM tusuario WHERE CONCAT (Nombre_Usuario,'',Id_Usuario )LIKE '%"+valor+"%'";
            model = new DefaultTableModel(null,titulos);
           try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                registros[0]=rs.getString("Id_Usuario");
                registros[1]=rs.getString("Nombre_Usuario");
                registros[2]=rs.getString("Usuario");
                registros[3]=rs.getString("Clave");
                registros[4]=rs.getString("Tipo_Usuario");
                registros[5]=rs.getString("Estatus");
                registros[6]=rs.getString("Correo_personal");
                registros[7]=rs.getString("Correo_institucional");
                registros[8]=rs.getString("Telefono_fijo");
                registros[9]=rs.getString("Telefono_celular");
                registros[10]=rs.getString("Carrera");
               model.addRow(registros);
            }
            tb_usuarios.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex );
        }
         con.Desconectar();  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ESTATUS = new javax.swing.ButtonGroup();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_usuarios = new javax.swing.JTable();
        Btn_Agregar = new javax.swing.JButton();
        Btn_Editar = new javax.swing.JButton();
        btn_regresa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_Usuario = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_clave = new javax.swing.JTextField();
        lb_telefono4 = new javax.swing.JLabel();
        Lb_nombredocente1 = new javax.swing.JLabel();
        lb_telefono5 = new javax.swing.JLabel();
        lb_Telefono3 = new javax.swing.JLabel();
        lb_email1 = new javax.swing.JLabel();
        btn_foto = new javax.swing.JButton();
        lbfoto = new javax.swing.JLabel();
        nombre_gradoestudios1 = new javax.swing.JLabel();
        ps_contra = new javax.swing.JPasswordField();
        cmb_estatus = new javax.swing.JComboBox<>();
        cmb_tu1 = new javax.swing.JComboBox<>();
        lb_telefono6 = new javax.swing.JLabel();
        lb_telefono7 = new javax.swing.JLabel();
        lb_telefono8 = new javax.swing.JLabel();
        lb_CorreoP = new javax.swing.JLabel();
        txt_Telefono1 = new javax.swing.JTextField();
        txt_Telefono2 = new javax.swing.JTextField();
        txt_CorreoP = new javax.swing.JTextField();
        txt_CorreoI = new javax.swing.JTextField();
        nombre_gradoestudios3 = new javax.swing.JLabel();
        cmb_carrera = new javax.swing.JComboBox<>();
        nombre_gradoestudios4 = new javax.swing.JLabel();
        cmb_eSTATUS2 = new javax.swing.JComboBox<>();
        txt_Imagen = new javax.swing.JTextField();
        lb_telefono9 = new javax.swing.JLabel();
        nombre_gradoestudios2 = new javax.swing.JLabel();
        txt_Aux = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel23.setText("Alta de Usuarios");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N

        tb_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_usuarios);

        Btn_Agregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        Btn_Agregar.setText("Agregar Nuevo Usuario");
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });

        Btn_Editar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        Btn_Editar.setText("Editar");
        Btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditarActionPerformed(evt);
            }
        });

        btn_regresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_regresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/door_in.png"))); // NOI18N
        btn_regresa.setText("Regresar");
        btn_regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresaActionPerformed(evt);
            }
        });

        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });
        txt_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UsuarioKeyTyped(evt);
            }
        });

        txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreKeyTyped(evt);
            }
        });

        txt_clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_claveKeyTyped(evt);
            }
        });

        lb_telefono4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_telefono4.setText("Clave de usuario:");

        Lb_nombredocente1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Lb_nombredocente1.setText("Nombre del Usuario:");

        lb_telefono5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_telefono5.setText("Contraseña");

        lb_Telefono3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_Telefono3.setText("Usuario");

        lb_email1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_email1.setText("Tipo de usuario");

        btn_foto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camara.png"))); // NOI18N
        btn_foto.setText("Agregar Foto");
        btn_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fotoActionPerformed(evt);
            }
        });

        lbfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbfoto.setText("Agregar foto");
        lbfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombre_gradoestudios1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nombre_gradoestudios1.setText("Estatus");

        ps_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_contraActionPerformed(evt);
            }
        });

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "NO ACTIVO" }));
        cmb_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estatusActionPerformed(evt);
            }
        });

        cmb_tu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALUMNO", "DOCENTE", "COORDINADOR", "ADMINISTRADOR" }));
        cmb_tu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tu1ActionPerformed(evt);
            }
        });

        lb_telefono6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_telefono6.setText("Telefono Fijo");

        lb_telefono7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_telefono7.setText("Telefono Movil");

        lb_telefono8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_telefono8.setText("Correo Institucional:");

        lb_CorreoP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_CorreoP.setText("Correo personal:");

        txt_Telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Telefono1KeyTyped(evt);
            }
        });

        txt_Telefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Telefono2KeyTyped(evt);
            }
        });

        txt_CorreoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CorreoPKeyTyped(evt);
            }
        });

        txt_CorreoI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CorreoIKeyTyped(evt);
            }
        });

        nombre_gradoestudios3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nombre_gradoestudios3.setText("Carrera");

        cmb_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UNA CARRERA...", "ADMINISTRACIÓN DE EMPRESAS", "ADMINISTRACIÓN DE EMPRESAS TURÍSTICAS", "ARQUITECTURA", "CIENCIA DE LA ACTIVIDAD FÍSICA Y DEL DEPORTE", "COMERCIO INTERNACIONAL", "COMUNICACIÓN", "CONTADURÍA", "CONTENIDOS DIGITALES INTERACTIVOS", "DERECHO", "DISEÑO GRÁFICO", "FISIOTERAPIA", "HIGIENISTA DENTAL", "INGENIERÍA EN LOGÍSTICA DEL TRANSPORTE", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "MERCADOTECNIA", "ODONTOLOGÍA", "PEDAGOGÍA", "PSICOLOGÍA CLÍNICA" }));
        cmb_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_carreraActionPerformed(evt);
            }
        });

        nombre_gradoestudios4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nombre_gradoestudios4.setText("Filtrar por:");

        cmb_eSTATUS2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "NO ACTIVO", "TODOS" }));
        cmb_eSTATUS2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_eSTATUS2ItemStateChanged(evt);
            }
        });
        cmb_eSTATUS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_eSTATUS2ActionPerformed(evt);
            }
        });

        txt_Imagen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ImagenKeyTyped(evt);
            }
        });

        lb_telefono9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_telefono9.setText("Ruta de Imagen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_telefono5)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_telefono4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lb_nombredocente1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_Telefono3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_telefono6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ps_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_CorreoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_CorreoI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nombre_gradoestudios1)
                                        .addGap(99, 99, 99)
                                        .addComponent(cmb_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lb_telefono7)
                                        .addGap(56, 56, 56)
                                        .addComponent(txt_Telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombre_gradoestudios3)
                                            .addComponent(nombre_gradoestudios4))
                                        .addGap(79, 79, 79)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmb_eSTATUS2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmb_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lb_email1)
                                        .addGap(50, 50, 50)
                                        .addComponent(cmb_tu1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_foto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_telefono9))))
                    .addComponent(lb_telefono8)
                    .addComponent(lb_CorreoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_telefono7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lb_telefono4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Lb_nombredocente1)
                                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb_Telefono3)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lb_telefono5)
                                            .addComponent(ps_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_foto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_CorreoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_CorreoP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lb_telefono8)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_CorreoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_telefono9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lb_telefono6)
                                        .addGap(14, 14, 14))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_tu1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_email1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombre_gradoestudios1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombre_gradoestudios3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_eSTATUS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombre_gradoestudios4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nombre_gradoestudios2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nombre_gradoestudios2.setText("Buscar");

        txt_Aux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AuxActionPerformed(evt);
            }
        });
        txt_Aux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_AuxKeyReleased(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disk.png"))); // NOI18N
        btn_guardar.setText("Guadar Cambios");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(btn_regresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Aux, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(nombre_gradoestudios2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Agregar)
                            .addComponent(btn_guardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_regresa)
                            .addComponent(Btn_Editar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nombre_gradoestudios2)
                            .addGap(29, 29, 29)
                            .addComponent(txt_Aux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed
       con = new conectar();
       Connection cn = con.getConnection();
        try{
            FileInputStream  archivofoto;
            if(txt_clave.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Ingrese la Clave de Usuario","error",JOptionPane.ERROR_MESSAGE); 
            }
             else if(txt_Nombre.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Ingrese el Nombre","error",JOptionPane.ERROR_MESSAGE); 
            }
            
             else if(txt_Usuario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Ingrese el Usuario","error",JOptionPane.ERROR_MESSAGE); 
            }
             else if(ps_contra.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Ingrese la Contraseña","error",JOptionPane.ERROR_MESSAGE); 
             
             }else if(txt_Telefono1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Ingrese el Telefono Fijo","error",JOptionPane.ERROR_MESSAGE); 
            }else if(txt_Telefono2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Ingrese el Telefono Movil","error",JOptionPane.ERROR_MESSAGE); 
            
            }else if(txt_CorreoP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Ingrese el Correo Personal Fijo","error",JOptionPane.ERROR_MESSAGE); 
            
            }else if(txt_CorreoI.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Ingrese el Correo Institucional","error",JOptionPane.ERROR_MESSAGE); 
            }else{
                
            
            PreparedStatement spt=cn.prepareStatement("INSERT INTO tusuario (Id_Usuario,Nombre_Usuario,Usuario,Clave,Tipo_Usuario,Estatus,Ruta,Fotografia,Correo_personal,Correo_institucional,Telefono_fijo,Telefono_celular,Carrera) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)");
            spt.setString(1, txt_clave.getText());
            spt.setString(2, txt_Nombre.getText());
            spt.setString(3, txt_Usuario.getText());
            spt.setString(4, ps_contra.getText());
            spt.setString(5, cmb_tu1.getSelectedItem().toString());
            spt.setString(6, cmb_estatus.getSelectedItem().toString());
            archivofoto = new FileInputStream(txt_Imagen.getText());
            spt.setBinaryStream(7, archivofoto );
            spt.setString(8, txt_CorreoP.getText());
            spt.setString(9, txt_CorreoI.getText());
            spt.setString(10,txt_Telefono1.getText());
            spt.setString(11,txt_Telefono2.getText());
            spt.setString(12,cmb_carrera.getSelectedItem().toString());
            spt.setString(13, txt_Imagen.getText());
            int N=spt.executeUpdate();
            if (N>0){
            JOptionPane.showMessageDialog(null,"Registro Guardado Exitosamente");
            }  }
            mostrarDatos("");
            }catch(Exception e){
                System.out.print(e.getMessage());
                                    }
        limpiar();
         con.Desconectar();    
    }//GEN-LAST:event_Btn_AgregarActionPerformed

    private void Btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditarActionPerformed
       con = new conectar();
       Connection cn = con.getConnection();
        int fila = tb_usuarios.getSelectedRow();
        
        
       lbfoto.setIcon(null);
 
        
        if(fila>=0){
            
            desbloquear();
            txt_clave.setText(tb_usuarios.getValueAt(fila, 0).toString());
            txt_Nombre.setText(tb_usuarios.getValueAt(fila, 1).toString());
            txt_Usuario.setText(tb_usuarios.getValueAt(fila, 2).toString());
            ps_contra.setText(tb_usuarios.getValueAt(fila, 3).toString());
            cmb_tu1.setSelectedItem(tb_usuarios.getValueAt(fila, 4).toString());
            cmb_estatus.setSelectedItem(tb_usuarios.getValueAt(fila, 5).toString());
            txt_CorreoP.setText(tb_usuarios.getValueAt(fila, 6).toString());
            txt_CorreoI.setText(tb_usuarios.getValueAt(fila, 7).toString());
            txt_Telefono2.setText(tb_usuarios.getValueAt(fila, 8).toString());
            txt_Telefono1.setText(tb_usuarios.getValueAt(fila, 9).toString());
            cmb_carrera.setSelectedItem(tb_usuarios.getValueAt(fila, 10).toString());
            //lbfoto.setIcon(tb_usuarios.get(fila, 11));
               
        }else{
            JOptionPane.showMessageDialog(null,"No se ha seleccionado nada");
            
        }
        
        con.Desconectar(); 
    }//GEN-LAST:event_Btn_EditarActionPerformed

    private void btn_regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresaActionPerformed
        Principal_Admin obj = new Principal_Admin();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_regresaActionPerformed

    private void btn_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fotoActionPerformed
        JFileChooser dlg= new JFileChooser();
        
        dlg.setFileFilter(filter);
        int option =dlg.showOpenDialog(this);
        if (option==JFileChooser.APPROVE_OPTION) {
            File file = dlg.getSelectedFile();
            txt_Imagen.setText(String.valueOf(file));
            Image foto =getToolkit().getImage(txt_Imagen.getText());
            foto = foto.getScaledInstance(175, 200,Image.SCALE_DEFAULT);
            lbfoto.setIcon(new ImageIcon(foto)); 
            
        }
        con.Desconectar(); 
    }//GEN-LAST:event_btn_fotoActionPerformed

    private void txt_claveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_claveKeyTyped

    }//GEN-LAST:event_txt_claveKeyTyped

    private void txt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreKeyTyped
       char c=evt.getKeyChar();
       if(Character.isLowerCase(c) ){
           String cad=(""+c).toUpperCase();
           c=cad.charAt(0);
           evt.setKeyChar(c);
       }
    }//GEN-LAST:event_txt_NombreKeyTyped

    private void txt_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsuarioKeyTyped
  
    }//GEN-LAST:event_txt_UsuarioKeyTyped

    private void txt_AuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AuxActionPerformed

    private void txt_AuxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AuxKeyReleased
        mostrarDatos(txt_Aux.getText());
    }//GEN-LAST:event_txt_AuxKeyReleased

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        con = new conectar();
       Connection cn = con.getConnection();   
       String sql = "UPDATE tusuario SET Nombre_Usuario='" + this.txt_Nombre.getText() + "',"
                                 + "Usuario='" + this.txt_Usuario.getText() + "',"
                                 + "Clave='" + this.ps_contra.getText() + "',"
                                 + "Correo_personal='" + this.txt_CorreoP.getText() + "',"
                                 + "Correo_institucional='" + this.txt_CorreoI.getText() + "',"
                                 + "Telefono_fijo='" + this.txt_Telefono1.getText() + "',"
                                 + "Estatus='" + this.cmb_estatus.getSelectedItem().toString() + "',"
                                 + "Carrera='" + this.cmb_carrera.getSelectedItem().toString() + "',"
                                 + "Fotografia='" + this.lbfoto.getIcon() + "',"
                                 + "Telefono_celular='" + this.txt_Telefono2.getText() + "' WHERE Id_Usuario='" + this.txt_clave.getText() + "'";
      
       try {
            PreparedStatement pps = (PreparedStatement) cn.prepareStatement(sql);
        pps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Actualizados", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            mostrarDatos("");
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null,"Error al Actualizar Datos", "Mensaje Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(abc_copia.class.getName()).log(Level.SEVERE, null, ex);
        }
        con.Desconectar(); 
        bloquear();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void ps_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ps_contraActionPerformed

    private void cmb_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_estatusActionPerformed

    private void cmb_tu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tu1ActionPerformed

    private void txt_Telefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Telefono1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Telefono1KeyTyped

    private void txt_Telefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Telefono2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Telefono2KeyTyped

    private void txt_CorreoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CorreoPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoPKeyTyped

    private void txt_CorreoIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CorreoIKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoIKeyTyped

    private void cmb_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_carreraActionPerformed

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsuarioActionPerformed

    private void cmb_eSTATUS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_eSTATUS2ActionPerformed
        if(cmb_eSTATUS2.getSelectedItem().equals("ACTIVOS")){
        
            DefaultTableModel dtm = new DefaultTableModel();
            ResultSet rs;
            try {
                dtm.addColumn();
            } catch (Exception e) {
            }
          
            
        }
    }//GEN-LAST:event_cmb_eSTATUS2ActionPerformed

    private void cmb_eSTATUS2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_eSTATUS2ItemStateChanged
      
        
    }//GEN-LAST:event_cmb_eSTATUS2ItemStateChanged

    private void txt_ImagenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ImagenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ImagenKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(abc_copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(abc_copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(abc_copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(abc_copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new abc_copia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_Editar;
    private javax.swing.ButtonGroup ESTATUS;
    private javax.swing.JLabel Lb_nombredocente1;
    private javax.swing.JButton btn_foto;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_regresa;
    private javax.swing.JComboBox<String> cmb_carrera;
    private javax.swing.JComboBox<String> cmb_eSTATUS2;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_tu1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_CorreoP;
    private javax.swing.JLabel lb_Telefono3;
    private javax.swing.JLabel lb_email1;
    private javax.swing.JLabel lb_telefono4;
    private javax.swing.JLabel lb_telefono5;
    private javax.swing.JLabel lb_telefono6;
    private javax.swing.JLabel lb_telefono7;
    private javax.swing.JLabel lb_telefono8;
    private javax.swing.JLabel lb_telefono9;
    private javax.swing.JLabel lbfoto;
    private javax.swing.JLabel nombre_gradoestudios1;
    private javax.swing.JLabel nombre_gradoestudios2;
    private javax.swing.JLabel nombre_gradoestudios3;
    private javax.swing.JLabel nombre_gradoestudios4;
    private javax.swing.JPasswordField ps_contra;
    private javax.swing.JTable tb_usuarios;
    private javax.swing.JTextField txt_Aux;
    private javax.swing.JTextField txt_CorreoI;
    private javax.swing.JTextField txt_CorreoP;
    private javax.swing.JTextField txt_Imagen;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Telefono1;
    private javax.swing.JTextField txt_Telefono2;
    private javax.swing.JTextField txt_Usuario;
    private javax.swing.JTextField txt_clave;
    // End of variables declaration//GEN-END:variables

}